# Generated by Django 3.0.5 on 2020-06-23 07:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200622_1217'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_path', models.TextField()),
                ('date_created', models.DateTimeField(default=datetime.datetime.now)),
                ('date_modified', models.DateTimeField(default=datetime.datetime.now)),
                ('public', models.BooleanField(default=True)),
                ('content', models.TextField()),
                ('content_formatted', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Snippet',
        ),
    ]
